package com.mylifemanager.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.webkit.*;import android.widget.FrameLayout;import java.util.*;

public class MainActivity extends Activity {
 private WebView webView; private ValueCallback<Uri[]> fileCallback; private WebChromeClient.FileChooserParams pendingParams; private Uri cameraUri;
 private static final int FILE_CHOOSER=41, REQ_NOTIF=42, REQ_CAMERA=43;
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().getDecorView().setSystemUiVisibility(android.view.View.SYSTEM_UI_FLAG_LAYOUT_STABLE);ReminderScheduler.ensureChannels(this);
  webView=new WebView(this);webView.setLayoutParams(new FrameLayout.LayoutParams(-1,-1));setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMediaPlaybackRequiresUserGesture(false);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);
  webView.addJavascriptInterface(new NativeNotificationBridge(this),"MLMNativeNotificationsNative");
  webView.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String url){super.onPageFinished(v,url);String js="window.MLMNativeNotifications={schedule:function(o){return Promise.resolve(MLMNativeNotificationsNative.schedule(JSON.stringify(o)))},cancel:function(o){return Promise.resolve(MLMNativeNotificationsNative.cancel(JSON.stringify(o)))},permissionStatus:function(){return Promise.resolve(MLMNativeNotificationsNative.permissionStatus())},requestPermission:function(){return Promise.resolve(MLMNativeNotificationsNative.requestPermission())}};window.dispatchEvent(new Event('mlm-native-ready'));";v.evaluateJavascript(js,null);}});
  webView.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;pendingParams=p;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},REQ_CAMERA);return true;}launchChooser(p);return true;}@Override public void onPermissionRequest(PermissionRequest r){runOnUiThread(()->{List<String> grant=new ArrayList<>();for(String x:r.getResources())if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(x)&&checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)grant.add(x);if(grant.isEmpty())r.deny();else r.grant(grant.toArray(new String[0]));});}});
  webView.loadUrl("file:///android_asset/index.html"); if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)new Handler(Looper.getMainLooper()).postDelayed(this::requestNotificationPermission,700);
 }
 public void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIF);}
 private void launchChooser(WebChromeClient.FileChooserParams p){Intent files;try{files=p.createIntent();}catch(Exception e){files=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);}ArrayList<Intent> initial=new ArrayList<>();try{ContentValues cv=new ContentValues();cv.put(MediaStore.Images.Media.DISPLAY_NAME,"MLM_"+System.currentTimeMillis()+".jpg");cv.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,cv);if(cameraUri!=null){Intent cam=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);cam.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);cam.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);if(cam.resolveActivity(getPackageManager())!=null)initial.add(cam);}}catch(Exception ignored){}
  Intent chooser=new Intent(Intent.ACTION_CHOOSER).putExtra(Intent.EXTRA_INTENT,files).putExtra(Intent.EXTRA_TITLE,"Choose file or camera");if(!initial.isEmpty())chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS,initial.toArray(new Intent[0]));startActivityForResult(chooser,FILE_CHOOSER);
 }
 @Override public void onRequestPermissionsResult(int req,String[] perms,int[] results){super.onRequestPermissionsResult(req,perms,results);if(req==REQ_CAMERA&&fileCallback!=null){launchChooser(pendingParams);pendingParams=null;}if(req==REQ_NOTIF&&webView!=null)webView.evaluateJavascript("window.dispatchEvent(new Event('mlm-native-ready'))",null);}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==FILE_CHOOSER&&fileCallback!=null){Uri[] result=null;if(resultCode==RESULT_OK){result=WebChromeClient.FileChooserParams.parseResult(resultCode,data);if((result==null||result.length==0)&&cameraUri!=null)result=new Uri[]{cameraUri};}else if(cameraUri!=null)try{getContentResolver().delete(cameraUri,null,null);}catch(Exception ignored){}fileCallback.onReceiveValue(result);fileCallback=null;cameraUri=null;pendingParams=null;}}
 @Override public void onBackPressed(){webView.evaluateJavascript("document.body.classList.contains('open')",v->{if("true".equals(v))webView.evaluateJavascript("setOpen(false)",null);else if(webView.canGoBack())webView.goBack();else MainActivity.super.onBackPressed();});}
 @Override protected void onDestroy(){if(webView!=null){webView.destroy();webView=null;}super.onDestroy();}
}
