plugins { id 'com.android.application' }

android {
    namespace 'com.mohan.mylifemanager'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mohan.mylifemanager'
        minSdk 24
        targetSdk 35
        versionCode 913103
        versionName '9.13.103'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
